'use client';import * as React from 'react';import { cn } from '@/lib/utils';
export const Button=React.forwardRef<HTMLButtonElement,React.ButtonHTMLAttributes<HTMLButtonElement>&{variant?:'default'|'outline'|'ghost'|'destructive';size?:'sm'|'icon'|'default'}>(({className,variant='default',size='default',type='button',...p},r)=><button ref={r} type={type} className={cn('inline-flex items-center justify-center gap-2 rounded-md text-sm font-medium transition focus-visible:outline focus-visible:outline-2 disabled:pointer-events-none disabled:opacity-50',variant==='default'&&'bg-primary text-primary-foreground hover:bg-primary/90',variant==='outline'&&'border bg-background hover:bg-accent',variant==='ghost'&&'hover:bg-accent',variant==='destructive'&&'bg-destructive text-destructive-foreground',size==='sm'&&'h-8 px-3',size==='icon'&&'h-9 w-9',size==='default'&&'h-9 px-4 py-2',className)} {...p}/>);Button.displayName='Button';
export function Card(p:React.HTMLAttributes<HTMLDivElement>){return <div {...p} className={cn('rounded-lg border bg-card text-card-foreground',p.className)}/>}export function Badge({className,...p}:React.HTMLAttributes<HTMLSpanElement>){return <span {...p} className={cn('inline-flex items-center gap-1 rounded-md border px-2 py-0.5 text-xs font-medium',className)}/>}export function Avatar({initials}:{initials:string}){return <span className="inline-flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-muted text-xs font-semibold">{initials}</span>}
export const Input=React.forwardRef<HTMLInputElement,React.InputHTMLAttributes<HTMLInputElement>>((p,r)=><input ref={r} {...p} className={cn('h-9 w-full rounded-md border bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-ring disabled:opacity-50 aria-[invalid=true]:border-destructive',p.className)}/>);Input.displayName='Input';
export const Textarea=React.forwardRef<HTMLTextAreaElement,React.TextareaHTMLAttributes<HTMLTextAreaElement>>((p,r)=><textarea ref={r} {...p} className={cn('min-h-24 w-full rounded-md border bg-background px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-ring aria-[invalid=true]:border-destructive',p.className)}/>);Textarea.displayName='Textarea';
export function Label(p:React.LabelHTMLAttributes<HTMLLabelElement>){return <label {...p} className={cn('text-sm font-medium',p.className)}/>}export function Field({children,error}:{children:React.ReactNode;error?:string}){return <div className="space-y-2">{children}{error&&<p className="text-sm text-destructive">{error}</p>}</div>}
export function Select({value,onChange,children,label}:{value:string;onChange:(v:string)=>void;children:React.ReactNode;label:string}){return <label className="grid gap-2 text-sm font-medium"><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)} className="h-9 rounded-md border bg-background px-3 text-sm">{children}</select></label>}
export function Switch({checked,onCheckedChange,id}:{checked:boolean;onCheckedChange:(v:boolean)=>void;id?:string}){return <button id={id} type="button" role="switch" aria-checked={checked} onClick={()=>onCheckedChange(!checked)} className={cn('h-6 w-11 rounded-full p-1 transition',checked?'bg-primary':'bg-muted')}><span className={cn('block h-4 w-4 rounded-full bg-background transition',checked&&'translate-x-5')}/></button>}
export function Progress({value}:{value:number}){return <div className="h-2 rounded-full bg-muted"><div className="h-2 rounded-full bg-primary" style={{width:`${value}%`}}/></div>}export function Skeleton({className}:{className?:string}){return <div className={cn('animate-pulse rounded-md bg-muted',className)}/>}export function Empty({title,desc,children}:{title:string;desc:string;children?:React.ReactNode}){return <div className="grid place-items-center gap-3 rounded-lg border border-dashed p-10 text-center"><h3 className="font-semibold">{title}</h3><p className="text-sm text-muted-foreground">{desc}</p>{children}</div>}
export function Dialog({open,onOpenChange,children}:{open:boolean;onOpenChange:(v:boolean)=>void;children:React.ReactNode}){if(!open)return null;return <div className="fixed inset-0 z-50 grid place-items-center bg-black/30 p-4" onMouseDown={()=>onOpenChange(false)}><div className="max-h-[90vh] w-full max-w-2xl overflow-auto rounded-lg bg-background p-6 shadow" onMouseDown={e=>e.stopPropagation()}>{children}</div></div>}export function Sheet({open,onOpenChange,children}:{open:boolean;onOpenChange:(v:boolean)=>void;children:React.ReactNode}){if(!open)return null;return <div className="fixed inset-0 z-50 bg-black/30" onMouseDown={()=>onOpenChange(false)}><aside className="ml-auto h-full w-full max-w-2xl overflow-auto bg-background p-6 shadow" onMouseDown={e=>e.stopPropagation()}>{children}</aside></div>}
export function Tabs({tabs,value,onChange}:{tabs:string[];value:string;onChange:(v:string)=>void}){return <div className="inline-flex rounded-lg bg-muted p-1">{tabs.map(t=><button key={t} onClick={()=>onChange(t)} className={cn('rounded-md px-3 py-1.5 text-sm',value===t&&'bg-background shadow')}>{t}</button>)}</div>}
